_wandb:
    value:
        cli_version: 0.22.0
        e:
            a4eviw3mrozl07bukkany0k27umhlejy:
                codePath: wandb_.py
                codePathLocal: wandb_.py
                email: duangsir518@163.com
                executable: /home/wang/anaconda3/envs/isaaclab2.2.0/bin/python
                git:
                    commit: 2a579de741dfd37507f1baecea02fa2f988513ee
                    remote: git@github.com:muzi2018/robot_lab.git
                host: ubuntu
                os: Linux-5.15.0-139-generic-x86_64-with-glibc2.31
                program: /home/wang/robot_lab/wandb_.py
                python: CPython 3.10.18
                root: /home/wang/robot_lab
                startedAt: "2025-09-27T08:33:51.315209Z"
                writerId: a4eviw3mrozl07bukkany0k27umhlejy
        m: []
        python_version: 3.10.18
        t:
            "3":
                - 2
                - 16
            "4": 3.10.18
            "5": 0.22.0
            "12": 0.22.0
            "13": linux-x86_64
epochs:
    value: 10
lr:
    value: 0.01
